### ISSUE TITLE
trouver le bon nom de domaine

### ISSUE THREAD

**Issue by dracdrac** [dracdrac/superjeu#1]
je propose ces noms de site (qui sont dispo):
superjeu.net
bonsjeux.net
bonjeu.net
jejeu.net
jeux.space
jeucool.net
jeanjean.space

**Comment by LeonLenclos** [comment]
Je selectionne :
- jejeu.net
- jeux.space
- superjeux.net

Je propose en plus :

- jejeu.org

**Comment by dracdrac** [comment]
waw trop dur

**Comment by LeonLenclos** [comment]
je te laisse choisir ou faire choisir. Vu que je commande à écrire des pages c'est cool si j'ai au moins le titre du site rapidement

**Comment by dracdrac** [comment]
http://unchevalhargneuxfaitfausseroute.net/ ?

**Comment by dracdrac** [comment]
http://jeujeu.org/ !

**Comment by LeonLenclos** [comment]
ok pour jeujeu.org

**Comment by dracdrac** [comment]
ben enfait je sais pas, JEJEU serait une bonne marque de fabrique, ou ou pourrait avoir un personnage, une sorte de JEANJEAN qui dirait son avis ou des conseil sur les jeu, une sorte de mascotte. 
jejeu joue

**Comment by dracdrac** [comment]
jeujeu.org ça fait peut etre trop les sites jeuxjeuxjeux.com pck les autres etaient pris

**Comment by LeonLenclos** [comment]
moi j'avoue que jaime bien jejeu. Car oui mascotte ou pas ça fait vraiment un nom original.
pour le nom de premier niveau je penche plus pour le .org car je trouve qu'on est plus une organisation a but non lucratif qu'un site vraiment lié au réseau et à internet (.net).

**Comment by dracdrac** [comment]
ok jejeu.org
