### ISSUE TITLE
Y'a quoi sur le site?

### ISSUE THREAD

**Issue by dracdrac** [dracdrac/superjeu#2]
des listes de jeux, triées par catégories, ex:
- jeux autour du table avec alcool
- jeux autour d'une table sans alcool
- jeux de dehors
- jeux entre amis
- jeux entre ennemis
- jeux coop
- jeux avec portable
- etc

pour trouver le bon jeu pour le bon moment

Quels jeux ont y met?
- les jeux qu'on invente et qu'on trouve bien
ex: jeu des mms
- les jeux auquels ont joue et qu'on trouve bien. 
ex: gabbo
- est ce qu'on met des jeux où il faut absolument acheter la boite pour y jouer?
ex: dobble

Mettrons nous à égal les jeux qu'on a créé et les jeux qu'on aime?

**Comment by LeonLenclos** [comment]
Ya quoi sur le site, proposition :
(proposition)

### Des jeux

Beaucoup de jeux. Chaque jeu est défini par : 
- Un nom
- Une courte description (max 250 caracteres)
- Une longue description (qui comprend les règles et tout et tout.)
- Une liste d'etiquettes (tags)

Et du coup déjà ya une page par jeu.

### Des listes de jeu

Donc il y a aussi plusieurs liste de jeux. en gros des liens vers les pages de chaque jeu avec la courte description.
- La liste de tous les jeux du site
- Une liste par etiquette 

#### Exemples d'etiquettes

- jeu sans materiel
- grands classique
- jeu à beaucoup
- plein air
- Jeux signés Jejeu
- Jeux par sms

**Comment by dracdrac** [comment]
oui
faudrait un truc de recherche comme pour trouver un appart:
combien de piece?
quel prix max?
balcon?

**Comment by dracdrac** [comment]
est ce qu'on integrerait pas twitter dans le site? 280 caractère max

**Comment by LeonLenclos** [comment]
Oui donc voilà. Au début je pensais à un systeme où en plus de :

> - Un nom
> -  Une courte description (max 250 caracteres)
> - Une longue description (qui comprend les règles et tout et tout.)
> - Une liste d'etiquettes (tags)

Quand tu entrerai un nouveau jeu tu mettrai aussi :

- Durée de la partie moyenne
- Nombre de joueur min
- Nombre de joueur max
- Materiel
- etc.
- etc.

L'avantage c'est que ducoup après on peut faire la recherche par nombre de joueur/ Durée de la partie/ etc/etc. Genre "ok jejeu trouve moi un jeu à jouer à 3 en moins de 30 minutes sans aucun materiel et qui convient à un enfant de 7 ans".

L'inconveniant c'est que tous les jeux ne peuvent pas être décrits simplement avec un nombre de joueur min et max. Par exemple le truco, tu mettrai quoi , min:4 max:6 sauf que on peut pas y jouer à 5. Pareil pour la durée de la partie et le reste. Enfin bref pour moi c'est l'embrouille. D'où ma proposition : 

Chaque jeu n'est décrit que par 4 champs (nom/description courte/description longue/liste d'etiquettes). Donc l'info du nombre de joueur par exemple elle est dans la description longue. Mais on peut aussi prévoir des etiquettes du genre *jouable à peu de joueurs*/*jouable à beaucoup de joueurs*/... . Du coup ba le mec qui cherche un "jeu à jouer à 3 en moins de 30 minutes sans aucun materiel et qui convient à un enfant de 7 ans" Soit il va fouiller dans la catégorie *jeux rapides" soit il va dans la catégorie "règles simples" soit il va dans la catégorie "sans matos" et il fouille.

C'est aussi pour que ce soit plus simples à programmer

**Comment by LeonLenclos** [comment]
> est ce qu'on integrerait pas twitter dans le site? 280 caractère max

Ouais grave. On fait un twitter-bot qui tweet chaque jour une description courte d'un jeu suivi d'un lien. C'est pas très compliqué à faire je crois ce genre de truc.

les liens des jeux ce sera genre jejeu.org/jeu.php?id=234 donc plus la descrition courte qui fait max 255 char on est pile dans les 280

**Comment by dracdrac** [comment]
ok

ou sinon on met une borne où il y a des chiffres de 0 à 10 (il doit bien des jeux auquel il n'y a aucun joueur) et une autre borne où tu peut soit ne rien mettre, soit mettre "ou plus" ou "ou moins".
Et entre les deux bornes on peut mettre le mot joueur(s).

X=borne vide.

- donc si tu choisi : "4" joueur(s) "X"
tu trouvera alors le truco dans la liste
- si tu choisi : "4" joueur(s) "ou plus"
tu trouvera alors le truco dans la liste aussi^^
- mais si tu choisi : "5" joueur(s) "ou plus"
ah ben tu trouvera le truco aussi...
- ah! mais si tu choisi : "5" joueur(s) "X"
yaura pas le truco! incroyable.

je sais pas si cest une solution

**Comment by dracdrac** [comment]
ah, et quand on dit "jeu sans materiel", on exclue les dés, le portable, les jeux de cartes classiques, etc..? les feuilles de papier? les stylos?
si oui, il nous faut les jeux avec matériel courant (dés / paquet de carte classique / papier stylo etc..)

=> on peut aussi faire une recherche de jeux par matériel que tu dispose:
tu peux chercher les jeux qui ont besoin d'un stylo, ou d'un paquet d'allumette etc..

**Comment by dracdrac** [comment]
On pourrais mettre un endroit où les gens peuvent nous contacter pour:
- signaler des erreurs d'orthographe
- signaler des problemes de regles de jeu ou d'incomprehension ou de regles pas tres claires 
- proposer un jeu (il pourrait remplir le formulaire mais qui passerait d'abord par nous)
- remercier les createurs du site
- envoyer un poke

**Comment by LeonLenclos** [comment]
oui !
